/*CREATE FUNCTION BUSCAR_POR_ID( numero ) RETURN VARCHAR(50)

BEGIN
SELECT CANTIDAD , PRECIO_VENTA
FROM PRODUCTOS 
WHERE PRODUCTOS.ID_PRODUCTO == numero;

RETURN 
END*/


/*-----SELECCIONAMOS SEGUN ID-------*/
SELECT *
FROM PRODUCTOS 
WHERE PRODUCTOS.ID_PRODUCTO = 1
ORDER BY PRODUCTOS.ID_PRODUCTO ASC;


/*-----SELECCIONAMOS SEGUN NOMBRE DEL PRODUCTO-------*/
SELECT NOMBRE, PRECIO_VENTA, PRECIO_VENTA 
FROM PRODUCTOS
WHERE PRODUCTOS.NOMBRE LIKE 'MARTI%' /*MARTILLO*/
ORDER BY NOMBRE;

/*-----SELECT PARA LISTADO DE CLIENTES-------*/
SELECT PERSONAS.* , CLIENTES.ID_CLIENTE, CLIENTES.NIT
FROM PERSONAS
INNER JOIN CLIENTES ON PERSONAS.ID_PERSONA = CLIENTES.ID_PERSONA
ORDER BY PERSONAS.ID_PERSONA ASC; 

/*-----SELECT PARA LISTAR A LOS EMPLEADOS--------*/
SELECT PERSONAS.* , EMPLEADOS.ID_EMPLEADO, EMPLEADOS.FECHA_CONTRATACION, EMPLEADOS.CARGO
FROM PERSONAS
INNER JOIN EMPLEADOS ON PERSONAS.ID_PERSONA = EMPLEADOS.ID_PERSONA
ORDER BY PERSONAS.ID_PERSONA ASC; 

/*-----SELECT PARA LISTAR A LOS PROVEEDORES--------*/
SELECT PERSONAS.* , PROVEEDORES.ID_PROVEEDOR, PROVEEDORES.ORG, PROVEEDORES.NO_CUENTA
FROM PERSONAS
INNER JOIN PROVEEDORES ON PERSONAS.ID_PERSONA = PROVEEDORES.ID_PERSONA
ORDER BY PERSONAS.ID_PERSONA ASC;




